version: "3.8"

services:
  readingisgooddb:
    image: mongo:latest
    container_name: readingisgooddb
    ports:
      - 27017:27017
  readingisgood:
    build: .
    container_name: readingisgood
    ports:
      - 8080:8080
    links:
      - readingisgooddb
