spring:
  application:
    name: reading-is-good
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}
      auto-index-creation: true
  profiles:
    active: local
